spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
  mvc:
    format:
      date: yyyy-MM-dd
  servlet:
    multipart:
      enabled: true
      #      最大支持文件大小
      max-file-size: 5MB
      #      最大支持请求大小
      max-request-size: 5MB

#头像文件存储路径
filepath: C:\Clark Software\JavaPersonalProject\diagon_alley\src\main\resources\static\images\portrait\small

#整合mybatis
#注意classpath:后面不能加/，否则就指向general这个目录了
mybatis:
  type-aliases-package: com.clark.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
